import type { AppData, Talk, TalkNotes } from "./types";

export const talks: Talk[] = [
  {
    id: "centro-manana-proposito-ingenieria",
    title: "El propósito de la ingeniería: ¿Crear herramientas o crear vida?",
    speaker: "Jesús Bossa",
    time: "9:00 AM",
    sortTime: 900,
    venue: "Sede Centro",
    block: "Mañana",
    language: "español",
    tags: ["ingeniería", "comunidad", "filosofía"],
    priority: "alta",
    defaultStatus: "pendiente",
  },
  {
    id: "centro-manana-kutti-e2e",
    title: "Who broke the build? Using Kutti to improve E2E testing and release faster",
    speaker: "Ram Mohan Rao Chukka, Shibi Ramachandran",
    time: "9:40 AM",
    sortTime: 940,
    venue: "Sede Centro",
    block: "Mañana",
    language: "inglés",
    tags: ["testing", "CI/CD"],
    priority: "media",
    defaultStatus: "pendiente",
  },
  {
    id: "centro-manana-security-developers",
    title: "Security for (not only openSUSE) developers",
    speaker: "Johannes Segitz",
    time: "10:25 AM",
    sortTime: 1025,
    venue: "Sede Centro",
    block: "Mañana",
    language: "inglés",
    tags: ["seguridad", "Linux"],
    priority: "alta",
    defaultStatus: "pendiente",
  },
  {
    id: "centro-manana-jupyter-educativos",
    title: "Jupyter en Entornos Educativos",
    speaker: "Andrea Navarro",
    time: "11:25 AM",
    sortTime: 1125,
    venue: "Sede Centro",
    block: "Mañana",
    language: "español",
    tags: ["educación", "datos", "Jupyter"],
    priority: "alta",
    defaultStatus: "pendiente",
  },
  {
    id: "centro-tarde-argocd-drift",
    title: "Beyond GitOps: Building Intelligent Drift Detection and Auto-Remediation in ArgoCD",
    speaker: "Ram Mohan Rao Chukka, Shibi Ramachandran",
    time: "1:00 PM",
    sortTime: 1300,
    venue: "Sede Centro",
    block: "Tarde",
    language: "inglés",
    tags: ["GitOps", "ArgoCD", "DevOps"],
    priority: "media",
    defaultStatus: "pendiente",
  },
  {
    id: "centro-tarde-nextgen-youth",
    title: "Rethinking Community: The NextGen Youth Path",
    speaker: "Douglas DeMaio",
    time: "1:45 PM",
    sortTime: 1345,
    venue: "Sede Centro",
    block: "Tarde",
    language: "inglés",
    tags: ["comunidad", "open source"],
    priority: "media",
    defaultStatus: "pendiente",
  },
  {
    id: "centro-tarde-visitchoco",
    title: "VisitChocó",
    speaker: "Deiner Bello",
    time: "2:45 PM",
    sortTime: 1445,
    venue: "Sede Centro",
    block: "Tarde",
    language: "español",
    tags: ["comunidad", "región", "tecnología"],
    priority: "media",
    defaultStatus: "pendiente",
  },
  {
    id: "norte-manana-kuna-red",
    title: "Kuna Red",
    speaker: "Luis Delascar",
    time: "9:00 AM",
    sortTime: 900,
    venue: "Sede Norte",
    block: "Mañana",
    language: "español",
    tags: ["comunidad", "red"],
    priority: "media",
    defaultStatus: "pendiente",
  },
  {
    id: "norte-manana-netfilter",
    title: "Netfilter Deep Dive: Arquitectura de Firewall en openSUSE",
    speaker: "Diego Córdoba",
    time: "9:40 AM",
    sortTime: 940,
    venue: "Sede Norte",
    block: "Mañana",
    language: "español",
    tags: ["firewall", "Linux", "seguridad"],
    priority: "alta",
    defaultStatus: "pendiente",
  },
  {
    id: "norte-manana-wazuh",
    title: "Observabilidad y Seguridad unificadas con Wazuh",
    speaker: "Walddys Dorrejo",
    time: "10:50 AM",
    sortTime: 1050,
    venue: "Sede Norte",
    block: "Mañana",
    language: "español",
    tags: ["observabilidad", "seguridad", "Wazuh"],
    priority: "alta",
    defaultStatus: "pendiente",
  },
  {
    id: "norte-manana-open-source-infra",
    title: "Open Source como Infraestructura",
    speaker: "Anuar Harb",
    time: "11:20 AM",
    sortTime: 1120,
    venue: "Sede Norte",
    block: "Mañana",
    language: "español",
    tags: ["open source", "infraestructura"],
    priority: "alta",
    defaultStatus: "pendiente",
  },
  {
    id: "norte-tarde-git-packaging",
    title: "An introduction to Git-based Packaging for OpenSUSE",
    speaker: "Gabriel Brazzoti",
    time: "1:00 PM",
    sortTime: 1300,
    venue: "Sede Norte",
    block: "Tarde",
    language: "inglés",
    tags: ["packaging", "openSUSE", "Git"],
    priority: "media",
    defaultStatus: "pendiente",
  },
  {
    id: "norte-tarde-great-migration",
    title: "The Great Migration?",
    speaker: "Patrick Fitzgerald",
    time: "1:45 PM",
    sortTime: 1345,
    venue: "Sede Norte",
    block: "Tarde",
    language: "inglés",
    tags: ["migración", "sistemas"],
    priority: "media",
    defaultStatus: "pendiente",
  },
  {
    id: "norte-tarde-selinux",
    title: "SELINUX the new mandatory access control system",
    speaker: "Johannes Segitz",
    time: "2:30 PM",
    sortTime: 1430,
    venue: "Sede Norte",
    block: "Tarde",
    language: "inglés",
    tags: ["SELinux", "seguridad", "Linux"],
    priority: "alta",
    defaultStatus: "pendiente",
  },
  {
    id: "norte-tarde-cierre",
    title: "Palabras de cierre Organizadores openSUSE Americas Summit Barranquilla 2026",
    speaker: "Organizadores openSUSE Americas Summit Barranquilla 2026",
    time: "3:20 PM",
    sortTime: 1520,
    venue: "Sede Norte",
    block: "Tarde",
    language: "mixto",
    tags: ["comunidad", "cierre"],
    priority: "media",
    defaultStatus: "pendiente",
  },
  {
    id: "ctf-laboratorio-redteam",
    title: "Cybersecurity Lab / Capture The Flag",
    speaker: "RedTeam Barranquilla",
    time: "Abril 29-30",
    sortTime: 1600,
    venue: "CTF",
    block: "Laboratorio",
    language: "mixto",
    tags: ["CTF", "seguridad", "Linux", "aprendizaje práctico"],
    priority: "alta",
    defaultStatus: "pendiente",
  },
];

export const emptyNotes: TalkNotes = {
  problem: "",
  keywords: "",
  usefulIdea: "",
  question: "",
  contacts: "",
  freeNotes: "",
};

export const initialData: AppData = {
  talkStatuses: Object.fromEntries(talks.map((talk) => [talk.id, talk.defaultStatus])),
  talkPriorities: Object.fromEntries(talks.map((talk) => [talk.id, talk.priority])),
  talkNotes: {},
  checklist: {
    event: [
      "laptop cargada",
      "cargador",
      "celular cargado",
      "datos móviles",
      "registro confirmado",
      "libreta/app de notas",
      "pregunta preparada",
    ].map((label, index) => ({ id: `event-${index + 1}`, label, checked: false })),
    ctf: [
      "confirmar reglas/scope",
      "elegir reto beginner",
      "abrir notas",
      "registrar IP/reto",
      "enumerar antes de explotar",
      "pedir pista si pasan 25 minutos bloqueado",
    ].map((label, index) => ({ id: `ctf-${index + 1}`, label, checked: false })),
  },
  ctfChallenges: [],
};
